variables:
  EOS_PATH: "/eos/user/h/hmei/www/dump/docs/"
  CI_OUTPUT_DIR: "public"

image: "python:3.9"

stages:
  - build
#  - static analysis
  - test
  - conda build
  - docs-gen
  - docs-deploy

#static_analysis:
#  stage: static analysis
#  before_script:
#    - pip install flake8
#  script:
#    - flake8 higgs_dna/*

build:
  stage: build
  script:
    - pip install -e .[dev]

unit_test:
  stage: test
  before_script:
    - pip install -e .[dev]
  script:
    - pwd
    - ls -l
    - export PYTHONPATH="$PYTHONPATH:."
    - python -c "import sys;print(sys.path)"
    - pytest

conda_build:
  stage: conda build
  image: continuumio/miniconda3:latest
  before_script:
  - conda env create -f environment.yml
  - source activate higgs-dna
  script:
    - pip install -e .

# Generate docs
docs-gen:
  stage: docs-gen
  image: gitlab-registry.cern.ch/ci-tools/ci-worker:cc7
  script:
  - yum -y install python3 pip3 locmap
  - pip3 install sphinx breathe sphinx_rtd_theme sphinx-argparse
  - mkdir "$CI_OUTPUT_DIR"
  - cd docs
  - make html
  - cd -
  - mv docs/build/html/* "$CI_OUTPUT_DIR"
  artifacts:
    paths:
    # Upload as an artifact the folder where the output has been generated
    # This will attach to the job the output. It can be browsed or downloaded
    - "$CI_OUTPUT_DIR"

# Deploy to an EOS folder the contents generated
deployment:
  stage: docs-deploy
  only:
    - master
  # Custom docker image providing the needed tools to deploy in EOS
  image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer:latest
  script:
    - deploy-eos
