variables:
  EOS_PATH: "/eos/user/h/higgsdna/www"
  CI_OUTPUT_DIR: "public"

image: "python:3.9"

stages:
  - build
  - build docker
  - static analysis
  - test

build:
  stage: build
  script:
    - pip install -e .[dev]

static_analysis:
  stage: static analysis
  before_script:
    - pip install flake8
    - pip install mypy --quiet
    - pip install -e.[dev]
  script:
    - flake8 higgs_dna/*
    # mypy will pick up what is specified in pyproject.toml
    #- mypy

unit_test:
  stage: test
  before_script:
    - pip install -e .[dev]
  script:
    - pwd
    - ls -l
    - export PYTHONPATH="$PYTHONPATH:."
    - python -c "import sys;print(sys.path)"
    - pytest
