image: continuumio/miniconda3:latest

before_script:
  - conda env create -f environment.yml
  - source activate higgs-dna
  - conda install flake8
  - conda install pytest

stages:
  - build
  - static analysis
  - test

static_analysis:
  stage: static analysis
  script:
    - flake8 higgs_dna/*

build:
  stage: build
  script:
    - pip install -e .[dev]

unit_test:
  stage: test
  script:
    - pwd
    - ls -l
    - export PYTHONPATH="$PYTHONPATH:."
    - python -c "import sys;print(sys.path)"
    - pytest
