image: "python:3.9"

stages:
  - build
  - build docker
  - tag docker
  - static analysis
  - test

include:
  - project: 'cms-analysis/general/container-image-ci-templates'
    file:
      - 'kaniko-image.gitlab-ci.yml'
      - 'skopeo.gitlab-ci.yml'

variables:
    CONTEXT_DIR: ""
    DOCKER_FILE_NAME: "Dockerfile"
    GIT_SUBMODULE_STRATEGY: recursive
    PUSH_IMAGE: "true"
    ACCELERATED_IMAGE: "true"
    BUILD_ARGS: ""
    SCAN_IMAGE: "false"

.build_docker_template:
  extends: .build_kaniko
  only:
    - pushes
    - merge_requests

build:
  stage: build
  script:
    - pip install -e .[dev]

build_docker:
  stage: build docker
  extends: .build_docker_template
  variables:
    BUILD_ARGS: "FROM_IMAGE=gitlab-registry.cern.ch/batch-team/dask-lxplus/lxdask-cc7:latest CLUSTER=lxplus"
    REGISTRY_IMAGE_PATH: ${CI_REGISTRY_IMAGE}:lxplus-${CI_COMMIT_SHORT_SHA}

build_docker_latest:
  stage: build docker
  extends: .tag_skopeo
  variables:
    IMAGE_ORIGIN_TAG: ${CI_REGISTRY_IMAGE}:lxplus-${CI_COMMIT_SHORT_SHA}
    IMAGE_DESTINATION_TAG: ${CI_REGISTRY_IMAGE}:lxplus-cc7-latest

static_analysis:
  stage: static analysis
  before_script:
    - pip install flake8
    - pip install mypy --quiet
    - pip install -e.[dev]
  script:
    - flake8 higgs_dna/*
    # mypy will pick up what is specified in pyproject.toml
    #- mypy

unit_test:
  stage: test
  before_script:
    - pip install -e .[dev]
  script:
    - pwd
    - ls -l
    - export PYTHONPATH="$PYTHONPATH:."
    - python -c "import sys;print(sys.path)"
    - pytest
