variables:
  EOS_PATH: "/eos/user/h/higgsdna/www"
  CI_OUTPUT_DIR: "public"

image: "python:3.9"

stages:
  - build
  - static analysis
  - test
  - docs-gen-conda-build
  - docs-deploy

static_analysis:
  stage: static analysis
  before_script:
    - pip install flake8
    - pip install mypy --quiet
  script:
    - flake8 higgs_dna/*
    - mypy higgs_dna
  allow_failure: true

build:
  stage: build
  script:
    - pip install -e .[dev]

unit_test:
  stage: test
  before_script:
    - pip install -e .[dev]
  script:
    - pwd
    - ls -l
    - export PYTHONPATH="$PYTHONPATH:."
    - python -c "import sys;print(sys.path)"
    - pytest

# Generate docs
docs-gen-conda-build:
  stage: docs-gen-conda-build
  image: continuumio/miniconda3:latest
  script:
    - conda install -c conda-forge mamba
    - mamba env create -f environment.yml
    - source activate higgs-dna
    - mamba install -c anaconda -c conda-forge sphinx breathe sphinx_rtd_theme sphinx-argparse nbsphinx ipython ipywidgets nbconvert=5.5.0 jinja2=3.0.3
    - mamba install pandoc
    - pip install -e .
    - cd docs/
    - sphinx-apidoc -o source/modules ../higgs_dna
    - sphinx-build source build/html
